# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AmericasVision' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'
  # pod 'FileExplorer'
  # pod 'Charts/Realm'
  pod 'Charts'
  # Pods for AmericasVision

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
